Printf get container
fmtlib/fmt pull request #1982
Opened 2020-11-05 14:19 UTC by rimathia

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

This affects the performance of fmt::sprintf in the case where the format string is at least on the order of 100 characters long.

The benchmark:

`#include <benchmark/benchmark.h>
#include <fmt/printf.h>

void long_argument(benchmark::State& state) {
  std::string long_string(state.range(0), 'A');
  for (auto _ : state) {
    benchmark::DoNotOptimize(fmt::sprintf("%s", long_string));
  };
}
BENCHMARK(long_argument)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);

void long_format_string(benchmark::State& state) {
  std::string format_string = std::string(state.range(0), 'A') + "%s";
  std::string message = "Hi";
  for (auto _ : state) {
    benchmark::DoNotOptimize(fmt::sprintf(format_string, message));
  };
}
BENCHMARK(long_format_string)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);

BENCHMARK_MAIN();`

The benchmark numbers:

![image](https://user-images.githubusercontent.com/7736877/98252034-c9148080-1f79-11eb-923d-cc44ace66bbc.png)

2020-11-05 15:30 UTC, vitaut commented
Thanks for the PR. Please fix formatting in the PR description and post benchmark results as text, not as image.

2020-11-05 16:57 UTC, rimathia commented
Thanks for getting to the PR so quickly. Just tell me if you'd like to have the json output as well.

2020-11-08 13:28 UTC, vitaut requested changes
Thanks for the PR.

The idea looks fine but I think you should use `fmt::detail::write` instead of reimplementing container/buffer detection.

2020-11-08 18:50 UTC, rimathia commented
I'll have to get back to this next week. Just to be sure I'm not operating on wrong assumptions: The following two benchmarks should have very similar results, right?

```c++
void long_printf_format_string(benchmark::State& state) {
  std::string format_string = std::string(state.range(0), 'A') + "%s";
  std::string message = "Hi";
  for (auto _ : state) {
    benchmark::DoNotOptimize(fmt::sprintf(format_string, message));
  };
}
BENCHMARK(long_printf_format_string)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);

void long_fmt_format_string(benchmark::State& state) {
  std::string format_string = std::string(state.range(0), 'A') + "{}";
  std::string message = "Hi";
  for (auto _ : state) {
    benchmark::DoNotOptimize(fmt::format(format_string, message));
  };
}
BENCHMARK(long_fmt_format_string)->Arg(10)->Arg(100)->Arg(1000)->Arg(10000);
```
On the branch (c4f62bf21158ec006f07cae373436635a492464e) the version with printf becomes quite a bit faster than the fmt version from 100 characters:
```
--------------------------------------------------------------------------
Benchmark                                Time             CPU   Iterations
--------------------------------------------------------------------------
long_printf_format_string/10          45.7 ns         45.6 ns     14294174
long_printf_format_string/100          116 ns          116 ns      6097242
long_printf_format_string/1000         405 ns          405 ns      1756349
long_printf_format_string/10000        870 ns          869 ns       775744
long_fmt_format_string/10             42.0 ns         42.0 ns     16111176
long_fmt_format_string/100             237 ns          237 ns      2903444
long_fmt_format_string/1000           1696 ns         1695 ns       401220
long_fmt_format_string/10000         13772 ns        13755 ns        50931
```

2020-11-08 23:56 UTC, vitaut commented
> The following two benchmarks should have very similar results, right?

Somewhat similar. The printf numbers look suspicious both compared to format and your earlier results. I recommend checking that the modified version produces the correct result.

2020-11-11 14:22 UTC, vitaut commented
I finally got a chance to look into this and the results are indeed correct. As it turned out `format_handler::on_text` wasn't going through the fast path which I fixed in https://github.com/fmtlib/fmt/commit/beb248b6ac4d366783305a25af47d52b03181cf8:

```
--------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
long_fmt_format_string           899 ns          899 ns       749016
```

Thanks for catching this!

My earlier comment about using `fmt::detail::write` still holds.

2020-11-12 11:03 UTC, rimathia commented
I have edited the top message to reflect the latest state, I hope this isn't too confusing.

2020-11-12 13:42 UTC, vitaut commented on include/fmt/printf.h
> +          out, basic_string_view<Char>(start, detail::to_unsigned(it - start)));
Why change this?

2020-11-12 14:15 UTC, vitaut requested changes

2020-11-12 14:15 UTC, vitaut commented on test/printf-test.cc
> +                 .count()));
This change seems unnecessary, please revert.

2020-11-12 14:15 UTC, vitaut commented on test/printf-test.cc
>  }
What is the purpose of this test? We should avoid adding more tests that rely too much on implementation details.

2020-11-12 16:05 UTC, vitaut commented on test/printf-test.cc
> +                 .count()));
This also looks unrelated, please revert (possibly submitting a separate PR to improve tests).

2020-11-12 16:37 UTC, merged

2020-11-12 16:37 UTC, vitaut commented
Thank you!

2020-11-12 16:39 UTC, rimathia commented
Thanks for your patience, I will try to get future pull requests to be more focused.