fix wrong order of expected and actual in truncated_printf_context te…
fmtlib/fmt pull request #2015
Opened 2020-11-12 16:48 UTC by rimathia

…st in PrintfDetermineOutputSize, make test of normal sprintf in a separate step

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

2020-11-12 16:50 UTC, rimathia commented
This is admittedly a very pedantic change, but when the test fails "expected" and "actual" are labeled as such in the output.

2020-11-13 13:40 UTC, vitaut requested changes
Thanks for the PR. GTest has moved away from this order of expected/actual (https://github.com/google/googletest/blob/master/googletest/docs/primer.md) so there is no need to reorder arguments:

> Historical note: Before February 2016 *_EQ had a convention of calling it as ASSERT_EQ(expected, actual), so lots of existing code uses this order. Now *_EQ treats both parameters in the same way.

2020-11-13 13:40 UTC, vitaut commented on test/printf-test.cc
> +  EXPECT_EQ(expected_size, fmt::sprintf(format_string, format_arg).size());
This can be removed since `sprintf` is tested elsewhere.

2020-11-13 20:22 UTC, rimathia commented
Because my assumption of one correct place for "actual" and "expected" in the test was wrong this is moot.

2020-11-13 20:22 UTC, closed without merging