Remove C++20 check from test/CMakeLists.txt
fmtlib/fmt pull request #2663
Opened 2021-12-18 16:51 UTC by alexezeder

This check disables entire branch of tests declaration unconditionally because `CXX_STANDARD` is not defined there. But even we use `CMAKE_CXX_STANDARD` there, these tests should work for standards >= C++20, IMHO.

`std-format-test` does not compile after enabling it. It's either outdated or should be still disabled. @vitaut, could you explain what should be done with it?

2021-12-19 16:43 UTC, vitaut requested changes
`std-format-test` is incompatible with C++20 so the check should be preserved but possibly moved to a place where it only applies to this test.

2021-12-20 17:17 UTC, alexezeder commented
I've disabled `std-format-test` with standards ≥ C++20, but there are still errors in `format` header.

2021-12-20 18:11 UTC, alexezeder commented
@vitaut, I suggest merging this PR to some temporary branch, where you can apply needed changes for `std-format-test` since I'm not sure that I can adapt it to the latest version of the library. Of course, you could guide me here by discussions, but it would be much faster for you to fix the remaining problems. What do you think about that?
Or we can simply disable `std-format-test` for now. In this case, I will create an issue to enable it again.

2021-12-23 19:10 UTC, vitaut commented
I removed `std-format-test` since the API it has been testing has already been merged into the standard.

2021-12-23 20:21 UTC, alexezeder commented
Rebased.

2021-12-23 20:31 UTC, vitaut approved these changes

2021-12-23 20:32 UTC, merged

2021-12-23 20:32 UTC, vitaut commented
Thank you