Don't explicitly delete copy ctor of dynamic_format_arg_store
fmtlib/fmt pull request #2664
Opened 2021-12-18 17:06 UTC by lucpelletier

Explicitly deleting the copy ctor causes the move constructor to not be
implicitly generated. This behaviour is different than what was in
v8.0.1 and causes code that relied on the move ctor of
dynamic_format_arg_store to break.

2021-12-18 17:38 UTC, vitaut commented
Thanks for the PR. Could you elaborate why you need a move ctor?

2021-12-18 18:22 UTC, lucpelletier commented
Yes, of course. I want to use Quill, which is a low-latency asynchronous logging library that uses fmtlib. The following class has a member of type dynamic_format_arg_store, and needs to support move operations:

https://github.com/odygrd/quill/blob/1386bff42eea9411600e58b9ddd682f1ec685c5a/quill/include/quill/detail/backend/BackendWorker.h#L211

2021-12-19 16:40 UTC, vitaut requested changes
Makes sense but please add a unit test for the move ctor in https://github.com/fmtlib/fmt/blob/master/test/args-test.cc.

2021-12-19 17:36 UTC, lucpelletier commented
Added test for move ctor. Did you also want a test for move assignment?

2021-12-20 19:22 UTC, phprus commented on test/args-test.cc
> +      std::make_unique<fmt::dynamic_format_arg_store<fmt::format_context>>();
``std::make_unique`` - C++14+

2021-12-20 19:35 UTC, lucpelletier commented on test/args-test.cc
> +      std::make_unique<fmt::dynamic_format_arg_store<fmt::format_context>>();
fixed

2021-12-23 19:34 UTC, vitaut approved these changes

2021-12-23 19:34 UTC, merged

2021-12-23 19:34 UTC, vitaut commented
Thank you