Make colored print handle UTF-8
fmtlib/fmt pull request #2701
Opened 2022-01-04 14:38 UTC by AlexGuteniev

Fixes #2681 

The working flow:
 * With `is_utf8()` calls `detail::print` that specifically converts to UTF-16 and calls `WriteConsoleW` 
 * Without `is_utf8()` calls `fwrite_fully`

The broken flow:
 * Always call `fputs`

The fix:
 * With `is_utf8()` call `detail::print` 
 * Without `is_utf8()` keep calling `fputs`, as `fwrite_fully` is not exported

Note that I'm not sure if the fix is correct on Linux or other platforms. On Windows `fputs` does not do any magic, and color sequences are processed by `WriteConsole`. If `fputs` actually does something, this part should be Windows-guarded.

2022-01-04 15:05 UTC, AlexGuteniev commented
I actually observe inconsistency that non-colored format throws I/O errors but colored directly calls `fputs` without checking. I'm not creating the issue yet, maybe it should be fixed within this change.

2022-01-06 23:27 UTC, vitaut requested changes
Thanks for the PR!

> I actually observe inconsistency that non-colored format throws I/O errors but colored directly calls fputs without checking. I'm not creating the issue yet, maybe it should be fixed within this change.

Good catch, please add an error check here or in a separate PR.

2022-01-06 23:27 UTC, vitaut commented on include/fmt/color.h
> +    detail::print(f, basic_string_view<Char>(buf.begin(), buf.size()));
Please wrap the body of the if statement in curly braces since else is braced.

2022-01-07 00:10 UTC, vitaut approved these changes

2022-01-07 00:10 UTC, merged