Add support for
fmtlib/fmt pull request #2941
Opened 2022-06-18 21:37 UTC by jehelset

2022-06-19 15:29 UTC, phprus commented
My suggestions:

Move ``variant.h`` content into ``std.h``.
Use  ``#ifdef __cpp_lib_variant`` instad of ``#if FMT_HAS_VARIANT``.

2022-06-20 20:01 UTC, vitaut commented
Thanks for the PR. This should definitely go to `fmt/std.h` and please fix build failures.

2022-06-22 04:39 UTC, jehelset commented
i rewrote `write_range_entry` from `fmt/range.h` as `write_variant_alternative`. since variant is C++17, i hoped i can could get away with if-constexpr instead, and compilers didn't complain. i just used `is_string` from `fmt/core.h` instead of this `is_std_string_like` in `fmt/ranges.h`, to not have to include or move code around. i also took the liberty of using `std::integral_sequence`, `std::void_t` and `std::conjuction`, and instead of checking for those library features i used the `__cpp_lib_variant` as a proxy. that's not quite correct, but i'm not sure what is the best approach.

2022-06-22 05:28 UTC, phprus commented on doc/api.rst
> +  #include <fmt/variant.h>
``#include <fmt/std.h>``

2022-06-22 06:31 UTC, jehelset commented on doc/api.rst
> +  #include <fmt/variant.h>
Thanks, fixed!

2022-06-23 15:08 UTC, vitaut requested changes

2022-06-23 15:08 UTC, vitaut commented on doc/api.rst
> +  // Prints "<'x'>"
Since variants don't have an established notation, I suggest using something more verbose here e.g. `variant('x')` instead of `<'x'>`.

2022-06-23 15:08 UTC, vitaut commented on doc/api.rst
> +  std::variant<std::monostate, char> v1{};
nit: `{}` is not needed here.

2022-06-23 15:08 UTC, vitaut commented on doc/api.rst
> +  // Prints "< >"
Empty variant could be represented as `variant()`.

2022-06-23 15:08 UTC, vitaut commented on include/fmt/std.h
> +template <typename VariantT, typename Char>
nit: VariantT -> Variant for consistency with `Char`.

2022-06-23 15:08 UTC, vitaut commented on include/fmt/std.h
> +  template <typename FormatContext = format_context>
I don't think you need a default here.

2022-06-23 15:12 UTC, vitaut commented
Overall looks good but I'd suggest changing the default representation to `variant(...)`. Also a few comments inline.

2022-06-23 17:21 UTC, powel-jeh commented on include/fmt/std.h
> +FMT_BEGIN_NAMESPACE
Fixed.

2022-06-23 17:28 UTC, jehelset commented
> Overall looks good but I'd suggest changing the default representation to `variant(...)`. Also a few comments inline.

If we can be verbose I would prefer to print `std::monostate` as `monostate`, and a variant holding a monostate as just `variant(monostate)`. Probably could do with some format specifiers, but I will leave that for someone more proficient.

2022-06-26 14:26 UTC, vitaut approved these changes

2022-06-26 14:28 UTC, merged

2022-06-26 14:28 UTC, vitaut commented
Thank you!