Add precision modifier for seconds in chrono format
fmtlib/fmt pull request #3122
Opened 2022-09-28 11:02 UTC by SappyJoy

Add precision modifier for seconds in chrono format and test for it.

It's became important for custom datetime types that store date, time and subseconds. I want to use chrono format for those types, but I have no way to control subsecond precision.

Use case:
```
EXPECT_EQ(fmt::format("{:%Y-%m-%d %H:%M:%.6S %Z}", datetime), "2022-09-28 12:14:25.123456 MSK");
```

2022-09-28 14:44 UTC, vitaut commented
Thanks for the PR. Is this feature part of the standard?

2022-10-01 14:22 UTC, vitaut requested changes
Thanks for the PR. Adding precision support to durations sounds reasonable but for consistency with the standard it should go at the beginning, not in `%S` (https://eel.is/c++draft/time.format), e.g.

```
fmt::print("{:.6%S}", std::chrono::nanoseconds{1234});
```

2022-10-05 09:15 UTC, SappyJoy commented
`{:.6%S}` looks like precision for _argument_. There is test for this:

```
  EXPECT_EQ("1.2 ms   ", fmt::format("{:7.1%Q %q}", dms(1.234)));
```

It is not obvious for user to use `{:.6%S}` and expect that this precision modifier belong to `%S`. But it can be done this way if the specifier has a higher priority on getting the modifier than the argument.

2022-10-08 17:59 UTC, vitaut commented
> But it can be done this way if the specifier has a higher priority on getting the modifier than the argument.

We should make existing precision apply to `%S` and not introduce a new one to avoid diverging too much from the standard.

2022-10-19 11:19 UTC, closed without merging

2022-10-19 11:32 UTC, SappyJoy commented
Oh, I squashed last commits to resolve conflict. It led to close this PR. Please **reopen** it, I made changes. Now it should work.

2022-10-19 16:39 UTC, vitaut commented
I am not able to reopen this diff for some reason. Please submit a new one.