Format unique_ptr with custom deleter
fmtlib/fmt pull request #3177
Opened 2022-11-12 18:47 UTC by hmbj

Added deleter type to fmt::ptr unique_ptr overload. Deleter type is part of the unique_ptr type.

2022-11-13 18:04 UTC, vitaut requested changes
LGTM but please apply clang-format.

2022-11-13 19:36 UTC, hmbj commented
> LGTM but please apply clang-format.

Cool. Ran clang-format on changed files.

2022-11-14 05:54 UTC, vitaut approved these changes

2022-11-14 05:54 UTC, merged

2022-11-14 06:03 UTC, vitaut commented
Thanks!