Add Optional
fmtlib/fmt pull request #3303
Opened 2023-02-11 07:56 UTC by tom-huntington

A formatter for `std::optional` as per https://github.com/fmtlib/fmt/issues/1367#issuecomment-1171254031

The code is just copied from barry's [slideware](https://www.youtube.com/watch?v=EQELdyecZlU) where the specifier just get parsed through to the formatter of the underling type.

As such there is no customization of printing of the optional's container for which I originally went with the opinionated `Some(...)` and `None`, but then changed to `Option(...)` and `Empty`? I'm not very convinced about `nullopt` when you're trying to study complicated output:
> {(50258, 0, None), (50364, 0, None), (538, 0, Some( by)), (428, 42, Some( your)), (9827, 100, Some( spell)), (11, 100, Some(,)), (457, 121, Some( but)), (4374, 100, Some( release)), (385, 142, Some( me)), (490, 156, Some( from)), (452, 168, Some( my)), (13543, 177, Some( bands)), (11, 260, Some(,)), (365, 264, Some( with)), (264, 268, Some( the)), (854, 270, Some( help)), (295, 282, Some( of)), (428, 290, Some( your)), (665, 300, Some( good)), (2377, 312, Some( hands)), (13, 350, Some(.)), (26214, 374, Some( Gentle)), (6045, 442, Some( breath)), (50816, 452, None), (50816, 452, None), (295, 1223, Some( of)), (6342, 487, Some( yours)), (452, 1380, Some( my)), (601, 622, Some( sa)), (4174, 1449, Some(ils)), ...

> {(50258, 0, Empty), (50364, 0, Empty), (538, 0, Option( by)), (428, 42, Option( your)), (9827, 100, Option( spell)), (11, 100, Option(,)), (457, 121, Option( but)), (4374, 100, Option( release)), (385, 142, Option( me)), (490, 156, Option( from)), (452, 168, Option( my)), (13543, 177, Option( bands)), (11, 260, Option(,)), (365, 264, Option( with)), (264, 268, Option( the)), (854, 270, Option( help)), (295, 282, Option( of)), (428, 290, Option( your)), (665, 300, Option( good)), (2377, 312, Option( hands)), (13, 350, Option(.)), (26214, 374, Option( Gentle)), (6045, 442, Option( breath)), (50816, 452, Empty), (50816, 452, Empty), (295, 1223, Option( of)), (6342, 487, Option( yours)), (452, 1380, Option( my)), ...

2023-02-11 10:57 UTC, tom-huntington commented
The current formatter for `std::variant` doesn't work for `wchar_t` formatting, and neither does this pull request.

I can't figure out a solution better than repeating the following for each literal
```
detail::string_literal<Char, 'O', 'p', 't', 'i', 'o', 'n'>{}
```

2023-02-12 08:32 UTC, phprus commented on include/fmt/std.h
> +      if constexpr (detail::is_string<T>::value) out = detail::write(out, '"');
We can use ``write_escaped_string`` to format an quoted string.

2023-02-12 20:05 UTC, ShawnZhong commented on test/std-test.cc
> +    "[104, 101, 108, 108, 111]");
I guess you want to test for `std::optional<std::vector<int>>`?

2023-02-18 15:29 UTC, vitaut requested changes
Thanks for the PR. For consistency with other formatters such as `variant` I suggest replacing `Option` with `optional` and use lowercase `empty` (or `none`).

2023-02-18 15:30 UTC, vitaut commented on include/fmt/std.h
> +template <class T, typename Char>
class -> typename

2023-02-18 15:31 UTC, vitaut commented on include/fmt/std.h
> +  static constexpr basic_string_view<Char> OPTION = detail::string_literal<Char, 'O','p','t','i','o','n','('>{};
Please apply clang-format.

2023-02-19 02:31 UTC, tom-huntington commented
> Thanks for the PR. For consistency with other formatters such as `variant` I suggest replacing `Option` with `optional` and use lowercase `empty` (or `none`).

@vitaut sure, I was just thinking you might rather want to change the variant formatter (despite capitalization going against the standard library's convention). For readability.

2023-02-20 17:54 UTC, vitaut requested changes

2023-02-20 17:54 UTC, vitaut commented on include/fmt/std.h
> +      detail::string_literal<Char, 'n', 'o', 'n', 'e'>{};
Let's make these names consistent with the content and fix naming conventions (we use lowercase for constants): OPTION -> optional, EMPTY -> none.

2023-02-23 05:56 UTC, tom-huntington commented on include/fmt/std.h
> +      }
I'm only guessing how to use `set_debug_format` correctly, but it seems to work

2023-02-24 15:50 UTC, vitaut commented on test/std-test.cc
> +#include "fmt/xchar.h"
std-test shouldn't include xchar.h. I you want to test wide strings, move the test to xchar-test.

2023-02-25 14:45 UTC, vitaut approved these changes

2023-02-25 14:45 UTC, merged

2023-02-25 14:46 UTC, vitaut commented
Thank you!