Fix for FMT_MODULE not compiling on GCC
fmtlib/fmt pull request #3605
Opened 2023-08-22 18:23 UTC by MathewBensonCode

Removing the friend function declaration has made compilation with FMT_MODULE succeed on GCC on linux. Also Tested with clang on linux 
and msvc on windows. 

They are all working.

2023-08-23 18:43 UTC, vitaut requested changes
Thanks for the PR.

Let's make this function not a friend and change the implementation to not access member variables (it should be very easy to do).

2023-08-23 22:21 UTC, MathewBensonCode commented
I hope this is what you had in mind.

2023-08-24 18:45 UTC, vitaut requested changes

2023-08-24 18:45 UTC, vitaut commented on include/fmt/format.h
>    return result;
Let's change this to something like:

```c++
auto hi = uint64_t();
auto lo = _umul128(x, y, &hi);
return {hi, lo};
```
and remove the new accessors.

2023-08-25 14:39 UTC, vitaut approved these changes

2023-08-25 14:44 UTC, merged