add meson instructions to usage docs
fmtlib/fmt pull request #3677
Opened 2023-10-09 17:10 UTC by fennewald

Adds a usage section for meson to the docs.

2023-10-14 14:05 UTC, vitaut requested changes
Thanks for the PR. Mostly looks good, just a few minor comments inline.

2023-10-14 14:05 UTC, vitaut commented on doc/usage.rst
> +Usage with meson
Meson should be capitalized.

2023-10-14 14:05 UTC, vitaut commented on doc/usage.rst
> +`Meson's wrapdb <https://mesonbuild.com/Wrapdb-projects.html>` includes a ``fmt``
Throughout the section:

wrapdb -> WrapDB

2023-10-14 14:05 UTC, vitaut commented on doc/usage.rst
> +If desired, ``fmt`` may be built as a static library, or as a headers-only
Here an below:

headers-only -> header-only

2023-10-16 17:39 UTC, fennewald commented
Changes applied and squashed into a single commit. Let me know if you'd like any other changes.

Thank you for the work you do maintaining this valuable library!

2023-10-18 18:53 UTC, vitaut approved these changes

2023-10-18 18:53 UTC, merged