Add support for CMake 3.28 C++ module features
fmtlib/fmt pull request #3679
Opened 2023-10-12 14:38 UTC by jcar87

CMake 3.28 ([rc1 announcement](https://www.kitware.com/cmake-3-28-0-rc1-is-ready-for-testing/)) adds support for C++ modules that is no longer experimental (so no need to add the experimental flags).

This PR adds support for this using the new features, when the build is configured with `FMT_MODULE` set to `ON` and the CMake version is 3.28 or higher.

Tested both building fmt, and then calling `cmake install` and using the fmt module from a different project. This works with:

* Linux, Clang 17, ninja 1.11.1
* Linux, gcc 13.1, ninja 1.11.1 (note that I'm using a patched version of gcc with dependency scanning support, and additional CMake variables since CMake expects gcc 14 for this, but gcc14 ICEs when building fmt as a module, I've reported this [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111785))
* Windows, msvc 19.37
  - Building fmt works with the Visual Studio generator or Ninja
  - Using the fmt module with `find_package(fmt)` works with Ninja, but not with the Visual Studio generator - will be reporting this to CMake

Hopefully this is OK. For CMake versions earlier than 3.28, this should behave as it was previously.

2023-10-14 14:07 UTC, vitaut requested changes
Thanks for the PR but the part of CMake you are changing is deprecated and will be removed. Please add this to `add_module_library` instead.

2023-10-15 10:43 UTC, jcar87 commented
Hi @vitaut - thanks for the review.
The changes in this PR _are_ mostly in `add_module_library()` - the only change in `enable_module()` is that I've added a conditional to skip the logic altogether when CMake is >= 3.28, as I can see that `enable_module()` is still called, and what it aims to do is already handled by CMake+ninja or by MSBuild.

However if this is not the best way, I'm happy to move the conditional out of `enable_module()` and into the two places where it is still called?

2023-10-15 15:38 UTC, vitaut commented
Sorry, I just realized that it's not super clear from the code and my comment but what I meant is that the source of truth of `add_module_library` is in https://github.com/vitaut/modules. Could you submit the change there to prevent it being overwritten in this repo next time we sync the two?

2023-11-13 16:34 UTC, vitaut approved these changes

2023-11-13 16:34 UTC, merged

2023-11-13 16:35 UTC, vitaut commented
I merged it for now but as commented earlier it will be overwritten unless also added to the main modules repo. Thanks!

2023-11-14 16:58 UTC, vitaut commented
Revered because of incompatibility with CMake 3.16: #3714.

2023-11-17 14:47 UTC, jcar87 commented
Apologies @vitaut - I will make the contribution in the main modules repo and make sure there's no regression with older CMake.

2023-11-18 21:10 UTC, vitaut commented
No worries and thanks for working on this.