Fix include xlocale
fmtlib/fmt pull request #3699
Opened 2023-11-02 17:25 UTC by hotwatermorning

I use fmtlib's fmt on some console game development environement, but os.h doesn't compile because of missing of xlocale.h.

Therefore I added `__has_include()` check before including xlocale.h.

Thanks.

2023-11-02 17:34 UTC, vitaut requested changes
Thanks for the PR

2023-11-02 17:46 UTC, hotwatermorning commented on include/fmt/os.h
> +#  if (__cplusplus < 201703L) || __has_include(<xlocale.h>)
@vitaut Hi, I changed the code to use FMT_HAS_INCLUDE and rebased on origin's master.

2023-11-02 18:02 UTC, vitaut approved these changes

2023-11-03 22:19 UTC, vitaut commented
Merged with a minor tweak, thanks.

2023-11-03 22:19 UTC, closed without merging