Added support of Swift Package Manager
fmtlib/fmt pull request #3841
Opened 2024-02-05 01:43 UTC by IhorShevchuk

This allows to add fmt as dependency to other Swift Packages or Xcode projects

2024-02-05 15:33 UTC, vitaut requested changes
Thanks for the PR. I think we could add a new package config but please put in the support directory where other contributed build/package configs reside.

2024-02-13 00:26 UTC, vitaut commented
@IhorShevchuk, do you plan to update this PR?

2024-02-13 00:40 UTC, IhorShevchuk commented
Hi @vitaut, sorry about the delay. Unfortunately Package.swift file must be located in root directory of the repository in order to other packages can see it and use.
I'll add documentation how to use it in another Swift Package or Xcode in `support/spm` folder. Also I guess it is a good idea to add build step in workflow

2024-02-13 14:31 UTC, vitaut commented
We shouldn't create an exception for Swift package manager so there are two options:
1. Put `Package.swift` in `support/spm` together with instructions/script how to move it - this is what we do for Bazel.
2. Create a separate repo with `Package.swift` in the top-level directory and fmt in a subdirectory, possibly as a submodule - this is similar to what most package managers do.

2024-02-16 03:31 UTC, IhorShevchuk commented
I see, than I would go with second option and create separate repository for fmt with Swift Package Manager. 
Thanks! I'll close this MR.

2024-02-16 03:31 UTC, closed without merging