Update CMakeLists.txt to support Emscripten
fmtlib/fmt pull request #3852
Opened 2024-02-15 11:18 UTC by danoli3

Allow for compile target for WASM Emscripten. 

Thanks FMT is wicked !

2024-02-17 14:41 UTC, vitaut requested changes
Thanks for the PR! Could you add a small section showing how to use this to the docs in https://github.com/fmtlib/fmt/blob/master/doc/usage.rst?

2024-02-17 14:41 UTC, vitaut commented on CMakeLists.txt
> +    add_executable(fmt_wasm
Why is it an executable and not a library.

2024-02-17 14:41 UTC, vitaut commented on CMakeLists.txt
> +    )
I don't think we need `FMT_WASM_SOURCES`, let's just use `${FMT_SOURCES}` and `${FMT_HEADERS}` in the target below.

2024-02-17 14:41 UTC, vitaut commented on CMakeLists.txt
> +if(EMSCRIPTEN)
nit: we normally put space after `if` so that it looks like a statement

2024-02-21 16:32 UTC, vitaut commented
@danoli3, could you add a small usage section per my earlier comment?

2024-02-21 16:35 UTC, sykhro commented
`fmt` already works on Emscripten without issues. What's the reason behind this PR?

2024-02-21 17:48 UTC, vitaut commented
I think @sykhro is right, at most you'd need to pass extra compile/link flags which can be done via CMake. We don't really need to introduce an extra target.

2024-02-21 17:48 UTC, closed without merging