Fix broken links in README.md
fmtlib/fmt pull request #4066
Opened 2024-07-11 05:30 UTC by zyctree

not sure it is needed to change https://fmt.dev/latest/ to https://fmt.dev/dev/，since https://fmt.dev/latest/ is still available

2024-07-11 13:03 UTC, vitaut requested changes
Thanks for the PR but please don't change `latest` to `dev`.

2024-07-12 06:03 UTC, zyctree commented
@vitaut updated

2024-07-12 18:21 UTC, vitaut approved these changes

2024-07-12 18:21 UTC, merged

2024-07-12 18:21 UTC, vitaut commented
Merged, thanks!