Address build failures when using Tip-of-Tree clang.
fmtlib/fmt pull request #4187
Opened 2024-10-02 22:33 UTC by zeroomega

When using ToT clang to build fmtlib, it complains 'sv' is not initialized by a constant expression. This patch addresses this issue.

2024-10-03 16:00 UTC, vitaut requested changes
Thanks for the PR!

2024-10-03 19:27 UTC, zeroomega commented on include/fmt/base.h
> +    auto sv = string_view(s);
I just revised it to use 'str' 
Hope the CI will pass.

2024-10-03 21:14 UTC, vitaut approved these changes

2024-10-03 22:51 UTC, zeroomega commented
Looks like all CI build passed.

2024-10-04 13:45 UTC, merged

2024-10-04 13:45 UTC, vitaut commented
Merged, thanks!