Fix compatibility with older versions of VS
fmtlib/fmt pull request #4271
Opened 2024-12-20 22:18 UTC by YexuanXiao

In the previous PR, I mentioned that there were no compatibility issues, but I was wrong. I confused the versions of VS and MSVC. _MSVC_STL_UPDATE appeared later than the VS version that fmt promised to support. This PR will fix this issue.

2024-12-21 15:32 UTC, vitaut commented on include/fmt/base.h
>  #endif
Let's move this to `ostream.h` where it is used.

2024-12-21 16:34 UTC, vitaut commented
Also to clarify: `_MSVC_STL_UPDATE` is only supported since MSVC 2019, right?

2024-12-21 20:38 UTC, YexuanXiao commented
> Also to clarify: `_MSVC_STL_UPDATE` is only supported since MSVC 2019, right?

To be precise, it has been supported since MSVC 19.12. Therefore, for versions from 19.00 to 19.12, use _MSVC_LANG instead. fmt has already declared that it does not support MSVC before version 19.00. Here are two version reference tables: [_MSC_VER](https://learn.microsoft.com/en-us/cpp/overview/compiler-versions?view=msvc-170) and [_MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE).

2024-12-22 15:01 UTC, vitaut commented on include/fmt/base.h
> +#endif
Could you also revert this unnecessary change to `base.h`?

2024-12-22 15:01 UTC, vitaut requested changes
Just one more minor comment, otherwise LGTM.

2024-12-23 15:26 UTC, vitaut approved these changes

2024-12-23 15:26 UTC, merged

2024-12-23 15:26 UTC, vitaut commented
Merged, thanks.